plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

base {
	archivesName = "cyberpunkcraft"
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"cyberpunkcraft" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureTests {
		createSourceSet = true
		modId = "cyberpunkcraft-test"
		enableGameTests = true
		enableClientGameTests = true
		// By setting this to true, you agree to the Minecraft EULA (https://aka.ms/MinecraftEULA).
		eula = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
